include:
  - ./beszel/docker-compose.yml
  - ./caddy/docker-compose.yml
  - ./community-fm/docker-compose.yml
  - ./copyparty/docker-compose.yml
  - ./frp/docker-compose.yml
  - ./glance/docker-compose.yml
  - ./gluetun/docker-compose.yml
  - ./immich/docker-compose.yml
  - ./memos/docker-compose.yml
  - ./pocket-id/docker-compose.yml
  - ./slskd/docker-compose.yml
  - ./tinyauth/docker-compose.yml
  - ./transmission/docker-compose.yml
  - ./wg-easy/docker-compose.yml
  - ./whoami/docker-compose.yml
