services:
  rathole:
    image: rapiz1/rathole:latest
    container_name: rathole-server
    restart: unless-stopped
    command: ["--server", "/app/config.toml"]
    configs:
      - source: rathole_config
        target: /app/config.toml
    ports:
      - "2333:2333"
      - "25565:25565"

configs:
  rathole_config:
    content: |
      [server]
      bind_addr = "0.0.0.0:2333"
      default_token = "${RATHOLE_TOKEN?}"

      [server.services.minecraft]
      bind_addr = "0.0.0.0:25565"
