services:
  beammp-server:
    image: rouhim/beammp-server
    container_name: beammp
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      - BEAMMP_PRIVATE
      - BEAMMP_MAX_CARS
      - BEAMMP_MAX_PLAYERS
      - BEAMMP_MAP
      - BEAMMP_NAME
      - BEAMMP_DESCRIPTION
      - BEAMMP_PORT
      - BEAMMP_DEBUG
      - BEAMMP_AUTH_KEY
      - TZ
    ports:
      - "${BEAMMP_PORT:-30814}:${BEAMMP_PORT:-30814}/tcp"
      - "${BEAMMP_PORT:-30814}:${BEAMMP_PORT:-30814}/udp"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
