# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:


[global]
  e2dsa  # enable file indexing and filesystem scanning
  e2ts   # enable multimedia indexing
  ansi   # enable colors in log messages (both in logfiles and stdout)
  og     # opengraph embeds
  grid   # grid view by default

  # trust ip given by reverse proxy in X-Forwarded-For header
  rproxy: 1

  # if we are confident that we got the docker-network config correct
  # (meaning copyparty is only accessible through traefik, and
  #  traefik makes sure that all requests go through authelia),
  # then accept X-Forwarded-For and IdP headers from any private IP:
  xff-src: lan

  # enable IdP support by expecting username/groupname in
  # http-headers provided by the reverse-proxy; header "X-IdP-User"
  # will contain the username, "X-IdP-Group" the groupname
  idp-h-usr: remote-user
  idp-h-grp: remote-groups

  # q, lo: /cfg/log/%Y-%m%d.log   # log to file instead of docker

  # p: 3939          # listen on another port
  # ipa: 10.89.      # only allow connections from 10.89.*
  # ipa: 172.16.4.0/23  # ...or only 172.16.4.* and 172.16.5.*
  # ipa: lan         # ...or allow LAN only; reject internet IPs
  # df: 16           # stop accepting uploads if less than 16 GB free disk space
  # ver              # show copyparty version in the controlpanel
  # grid             # show thumbnails/grid-view by default
  # theme: 2         # monokai
  # name: datasaver  # change the server-name that's displayed in the browser
  # stats, nos-dup   # enable the prometheus endpoint, but disable the dupes counter (too slow)
  # no-robots, force-js  # make it harder for search engines to read your server

  # enable version-checking by uncommenting one of the vc-url lines below;
  # shows a warning-banner in the controlpanel if your version has a known vulnerability
  # vc-url: https://api.github.com/repos/9001/copyparty/security-advisories?per_page=9
  # vc-url: https://api.copyparty.eu/advisories
  # vc-exit  # panic and shutdown instead of just showing the warning


[/]           # create a volume at "/" (the webroot), which will
  /public     # share /w (the docker data volume)
  accs:
    r: *         # everyone gets read-access, but
    rwmd: @acct  # the group "acct" gets read-write-move-delete-admin

[/private]     # create a volume at "/private", which will
  /private     # share /private (the docker data volume)
  accs:
    g: *         # everyone gets (only download files, cannot see folder contents)-access, but
    rwmd: @acct  # the group "acct" gets read-write-move-delete-admin

[/downloads]     # create a volume at "/downloads", which will
  /downloads     # share /downloads (the docker data volume)
  accs:
    g: *         # everyone gets (only download files, cannot see folder contents)-access, but
    rwmd: @acct  # the group "acct" gets read-write-move-delete-admin

[/music]     # create a volume at "/music", which will
  /music     # share /music (the docker data volume)
  accs:
    g: *         # everyone gets (only download files, cannot see folder contents)-access, but
    rwmd: @acct  # the group "acct" gets read-write-move-delete-admin
