services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - "../data/navidrome:/data"
      - "../share/music/library:/music:ro"

  feishin:
    image: "ghcr.io/jeffvli/feishin:latest"
    container_name: feishin
    restart: unless-stopped
    environment:
      - SERVER_NAME=navidrome # pre-defined server name
      - SERVER_LOCK=true # When true AND name/type/url are set, only username/password can be toggled
      - SERVER_TYPE=navidrome # the allowed types are: jellyfin, navidrome, subsonic. These values are case insensitive
      - SERVER_URL=http://navidrome:4533 # http://address:port or https://address:port
      - LEGACY_AUTHENTICATION=false # When SERVER_LOCK is true, sets the legacy (plaintext) authentication flag for Subsonic/OpenSubsonic servers
      - ANALYTICS_DISABLED=true # Set to true to disable Umami analytics tracking
