services:
  frps:
    image: snowdreamtech/frps:latest
    container_name: frps
    restart: unless-stopped
    network_mode: host
    configs:
      - source: frps-config
        target: /etc/frp/frps.toml

configs:
  frps-config:
    content: |
      bindPort = 7000

      auth.method = "token"
      auth.token = "${FRP_TOKEN?}"
