- name: Home
  columns:
    - size: small
      widgets:
        - type: server-stats
          servers:
            - type: local
              name: Services

        - type: custom-api
          title: VPN
          cache: 1m
          url: http://gluetun:8000/v1/publicip/ip
          headers:
            x-api-key: ${GLUETUN_API_KEY}
          subrequests:
            port:
              url: http://gluetun:8000/v1/portforward
              headers:
                x-api-key: ${GLUETUN_API_KEY}
          template: |
            <a href="https://ipinfo.io/{{ .JSON.String "public_ip" }}" target="_blank"><p class="size-h2 color-paragraph text-center">{{ .JSON.String "public_ip" }}</p></a>
            <p class="size-h1 color-paragraph text-center">{{ (.Subrequest "port").JSON.String "port" }}</p>

        - type: calendar
          first-day-of-week: monday

    - size: full
      widgets:
        - type: monitor
          cache: 1m
          title: Infrastructure
          sites:
            - title: Pocket ID
              icon: sh:pocket-id
              url: https://id.${DOMAIN}/
              check-url: http://pocket-id:1411

            - title: Tinyauth
              icon: di:tinyauth
              url: https://auth.${DOMAIN}/
              check-url: http://tinyauth:3000

            - title: Gluetun
              icon: sh:gluetun
              check-url: http://gluetun:9999

            - title: Beszel
              icon: sh:beszel
              url: https://beszel.${DOMAIN}/
              check-url: http://beszel:8090

        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Copyparty
              icon: sh:copyparty
              url: https://files.${DOMAIN}/
              check-url: http://copyparty:3923

            - title: Memos
              icon: di:memos
              url: https://memos.${DOMAIN}/
              check-url: http://memos:5230

            - title: slskd
              icon: sh:slskd
              url: https://slskd.${DOMAIN}/
              check-url: http://gluetun:5030

            - title: Transmission
              icon: sh:transmission
              url: https://transmission.${DOMAIN}/
              check-url: http://gluetun:9091

            - title: Immich
              icon: sh:immich
              url: https://immich.${DOMAIN}/
              check-url: http://immich-server:2283

            - title: 4get
              icon: /assets/4get.png
              url: https://search.${DOMAIN}/
              check-url: http://fourget:80

            - title: community.fm
              icon: /assets/yeah.png
              url: https://radio.${DOMAIN}/
              check-url: http://community-fm-icecast:8000

            - title: Wireguard
              icon: sh:wireguard
              url: https://wg.${DOMAIN}/
              check-url: http://wg-easy:80

            - title: Chatto
              icon: /assets/chatto.webp
              url: https://chat.${DOMAIN}/
              check-url: http://chatto-server:4000

    - size: small
      widgets:
        - type: repository
          repository: ${GITHUB_REPO}
          token: ${GITHUB_PAT}
          commits-limit: 10
