services:
  glance:
    image: glanceapp/glance
    container_name: glance
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN?}
      - GLUETUN_API_KEY=${GLUETUN_API_KEY?}
      - GITHUB_REPO=${GITHUB_REPO?}
      - GITHUB_PAT=${GITHUB_PAT?}
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
